name: .Net Swap Deployment

on:
  release:
    types: [published]

jobs:
  swap-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Check .Net Staging Health Status
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://openhackscu6b3d6poi-staging.azurewebsites.net/api/healthcheck/poi
        follow-redirect: no
        max-attempts: 3
        retry-delay: 30s
    # Login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Swap User Profile STAGING -> PROD using Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp deployment slot swap  -g openhackscu6b3d6rg -n openhackscu6b3d6poi --slot staging --target-slot production
    - name: Check Node PROD Health Status
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://openhackscu6b3d6poi.azurewebsites.net/api/healthcheck/poi
        follow-redirect: no
        max-attempts: 3
        retry-delay: 90s
    - name: If failure Rollback PROD -> STAGING using Azure CLI
      uses: azure/CLI@v1
      if: ${{ failure() }} 
      with:
        inlineScript: |
          az webapp deployment slot swap  -g openhackscu6b3d6rg -n openhackscu6b3d6poi --slot production --target-slot staging
